server:
  port: 9090
  address: 0.0.0.0

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    # sql 语句打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1  #已删除
      logic-not-delete-value: 0  #未删除
  type-enums-package: mybatisPlus.enums #配置枚举包扫描
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: NIE(vyK3r+9yZG6xS4KlpPp+ffvOXSHIhx98d5f6PhRzeuy+G00oR6l+r0rEiDwQuZrrIeHIfhibycLToLUj2hn3ZKOcBbv/Iu47RHflipssSZYGoY/YlgcKfDo/op5PACYBsWpkybx/kg7viOESRH5vL3grUuO/cLoPo7TrZD3hTusDmnjCmDSbw28NJN8UE5qhoAY3HwlSR2AZNYoEctRslA==)
      username: NIE(RFymkRNkUKxRSSnggHSZKaUMuiwz5AH/UpwyilI5hYK9ID8ayBIgj88Yz+y7JDjq)
      password: NIE(Bemk3aSkJm56SUQKeXBQLgCUN2xgFPLsX8tVW3cyZlreVMOW+TtvyAGxSamY86B6)
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
  redis:
    host: 81.69.45.15
    port: 6379
    password: NIE(Bemk3aSkJm56SUQKeXBQLgCUN2xgFPLsX8tVW3cyZlreVMOW+TtvyAGxSamY86B6)
    database: 0
  rabbitmq:
    host: 81.69.45.15
    port: 5672
    username: NIE(BfiSm1/21faEo56nK+ohEP1il8gBnNNTySpFrI+P2TJFPV2lV1QxFzy9w2VxgFCA)
    password: NIE(Bemk3aSkJm56SUQKeXBQLgCUN2xgFPLsX8tVW3cyZlreVMOW+TtvyAGxSamY86B6)
    publisher-confirm-type: correlated
    virtual-host: /
    #开启ACK
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
  application:
    name: spring-boot11


transmission:
  kafka-offset-prefix: "kafka:offset:${spring.application.name}-202208211200"
  subscribe-name: "nanjingjxz-dev-e2r_v2x_up_vehicle_realtime,nanjingjxz-dev-e2r_v2x_up_vehicle_realtime_event,nanjingjxz-dev-e2r_v2x_up_mec_event,nanjingjxz-dev-e2r_v2x_up_mec_condition,nanjingjxz-dev-e2r_v2x_up_mec_ptc"
  poll-timeout-ms: 1000
  consumer:
    bootstrap.servers: 192.168.59.86:9092
    group.id: ${spring.application.name}-202208230915
    enable.auto.commit: false
    auto.offset.reset: latest
    max.poll.records: 5000
    max.partition.fetch.bytes: 1048576
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    bootstrap.servers: 192.168.59.86:9092
    acks: "1"
    linger.ms: 500
    retries: 0
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.apache.kafka.common.serialization.StringSerializer

jasypt:
  encryptor:
    property:
      prefix: 'NIE('
      suffix: ')'

logging:
  config: classpath:logback-spring.xml
